---
title: "Unifying traits"
editor: 
  markdown: 
    wrap: sentence
---

## **Copy-and-paste** 

You have multiple lives.
For every **3 max HP** you have you have **1 Respawn** (**10 HP** would be **4 Respawns**).

Each life you have has **3 HP**, you can never have higher than this.

When you die you spawn in a place of your choice within 10 feet of your dead body, using one of your respawns.
You are only wearing basic clothing, needing to retrieve your **Equipment** from your dead body.
If you **die** with 0 respawns your character is dead forever.

You may use a **Level up reward** to replace every previous instance of 3 in this trait description to 6.
Additionally, gain **+4 max HP**.

Revolver (1D6+1 DAMAGE) & **+1 JAWS**

## **Ettin** 

You have 2 heads.
Whilst you have at least one head you will survive.

You can spend one head as an **Accessory**.

Whilst you only have one head you gain **+1 JAWS**, **+1 LIMBS**, **-2 EYES,** and **-1 NERVES**.

**Mission end:** A destroyed head grows back.

Telescopic goggles and Bolt-action rifle (1d6+1 DAMAGE) & **+2 NERVES**

## **Microbiota control** 

You are able to somewhat control the microbiota on and in your body (bacteria, archaea, & fungi).
You can medicate yourself and are immune to ingested poisons.

**Once per mission** you can share your microbiome with one nearby target.
This lasts as long as you both share the same air or till the end of the current mission.

Microbiology kit & **+1 NERVES**

## **Overgrown** 

You are covered in ivy and various other plants.
These plants are connected to you feeding off your nutrients as it shares its energy with you in a symbiotic relationship.
You may use the plants in various ways including as camouflage and using the ivy to rappel with.

**Once per mission** you can choose a type of plant to rapidly grow from you.

**Mission end:** Your plants grow back if they are somehow destroyed.

Machete (1D6 DAMAGE) & **+1 NERVES**

## **Polyglot** 

You are fluent in the reading, writing, and speaking of 3 times your **NERVES** attribute additional languages.
You can also understand all other languages to a limited degree.
When reading, writing, or communicating in a language you are not fluent in you and the referee can only speak with single syllable words.
If you use a multi syllable word the referee may give you a complication.

Remote covert listening device and headphone & **+2 EYES**

## **Suited-creature** 

You are a small sentient living entity in a humanoid sized and shaped suit.
You could be a worm in a suit from the gods, a little alien in a human robot, a goldfish in a fishbowl as the head of an iron golem etc.
Choose what type of small entity you are and what type of suit you have.
You may freely leave the suit.
When you leave the suit you are still sentient and have **3HP**.

Robot suit (1 ARMOR) & **+1 LIMBS**