---
title: "ALLIES & NEMESES"
editor: 
  markdown: 
    wrap: sentence
---

A large part of the fun of running **PUML** is collaborating on the creation of the **Allies** & **Nemeses** with your **players**.
You should encourage the imagination of the **player** whilst informing them of your setting and its tone.
The **Player** should in turn create **characters that** fit into yoursetting and allow you the freedom to create **character stat blocks** you would enjoy running.

**Allies** can be used during down time to create narrative moments with your **player’s PCs**.
It is the responsibility of the players to call in their **Allies** during missions.

A **Nemesis** arrives into the action due to the **Nemesis dice** when a **player** calls for **Ally** assistance.
However, this does not limit the use of **Nemeses**.
I encourage you to incorporate **Nemeses** into your campaign.
Allow a **Nemesis** to be the big bad of a campaign.
Maybe the **Nemeses** of the **players** all work for one evil organisation.
The **Nemesis** does not need to directly interfere in a mission, they could send henchmen, provide weapons to the mission **enemies**, or hack the **PCs’ Equipment**.
Don’t be afraid to have cutaway scenes showing a **Nemesis** in their lair mistreating their minions, spouting evil monologues, or scheming with other **Nemeses**.
Use the Nemeses as you see fit incorporating suggestions from the players.

\
If this seems like a lot then take things slow.
I like to run a few adventures and see how the characters develop.
Then as inspiration hits I incorporate the **PCs**, **Allies**, and **Nemeses** into the campaign plans.
Of course try to create loose plans to allow the players’ actions to change it.
