# FIST Partial successes

Below are random tables for partial successes based on the table from the Fist: Ultra Edition page 148.

## General

1. You can't move right now
2. You cannot finish it alone
3. You deplete a resource
4. You ignore something else
5. You need more time
6. You’ll need to rest a moment

## Mental

1. Approximate calculations only
2. More research is required
3. Some information is lost
4. You can’t remember exactly
5. You don’t know why you’re right
6. You failed to account for...

## Movement

1. You drop an important item
2. You go partially off-course
3. You hurt yourself a little
4. You must take a longer route
5. You’re now in harm’s way
6. You’re stopped halfway

## Social

1. Disarm yourself immediately
2. That won’t work again
3. You must prove yourself
4. You must provide compensation
5. You need to make a hard sell
6. SOCIAL You’ll be watched constantly

## Weird

1. A trait behaves erratically
2. Turn on your teammates
3. You begin losing your grip
4. You get a bad nosebleed
5. You slowly develop a new trait
6. You’re struck by lightning