# FIST Weapon tags

D66 weapon tags

**11. ACCURATE:** Scoped, sighted, or well-balanced; this weapon grants one automatic success when attacking per mission.

**12. ANTI-MATERIEL:** Deals double DAMAGE to vehicles and structures; cumbersome to carry around.

**13. ALT-FIRE:** This weapon has a secondary component or form which also deals damage, (e.g. bayonet, launcher attachment, sword that becomes a whip).

**14. ARMOR-PIERCING:** Attacks with this weapon ignore ARMOR bonuses granted by physical means.

**15. BANE:** Forged from (or fires) a magically useful material of your choice (silver, salt, etc.) Deals double DAMAGE to those affected.

**16. COLLAPSIBLE:** Easily concealed, no matter the size; will never be detected during pat-downs.

**21. CURSED:** Requires powerful magic to remove once equipped. The wielder may permanently spend 1D6 MAX HP to guarantee a successful attack.

**22. CUSTOMIZED:** Deals an additional 1 DAMAGE and has a weapon skin; coveted by enemies.

**23. DUMMY:** Appears to be a weapon, but is actually another mundane item of your choice (e.g. gun lighter, fake sword with a hidden compartment).

**24. ELECTRIFIED:** Deals double DAMAGE to robots and other complex machines. Shorts out running electronics and briefly electrifies bodies of water.

**25. EXPERIMENTAL:** When each mission begins, roll D66 on this table for the weapon’s effect (if you get EXPERIMENTAL, create a new one with the ref).

**26. FLASHY:** If you describe a unique and bombastic attack with this weapon, you can roll +NERVES to hit.

**31. GRIP:** Custom materials and ergonomic design; the referee can never state that you drop this weapon.

**32. HEAVY:** This thing is too big to be called a weapon. Once per mission, take +3 on a JAWS roll that involves this weapon.

**33. HUD:** Scans hostiles. When you kill something new, the referee will tell you a useful fact about it.

**34. ICE:** Makes surfaces slick and deals double DAMAGE to anything that requires warmth to function.

**35. INCENDIARY:** When damage is dealt, this weapon also deals 2 DAMAGE to anything within firespreading range. Deals double DAMAGE to plants.

**36. INDESTRUCTIBLE:** Impervious to everything; can withstand any amount of pressure or corrosion.

**41. LIGHT:** Weighs almost nothing. Grants +1 on LIMBS rolls that involve this weapon.

**42. LOUD:** Attacks with this weapon draw the undivided attention of enemies within earshot (and instantly reveal your position).

**43. LUCKY:** Rolling an ultra success while attacking with this weapon grants the user one PRIMAL DIE.

**44. MEDICAL:** Once per mission, you may use this weapon to deal negative DAMAGE, healing the target.

**45. MESSY:** Enemies explode into gore/goo/scrap etc. on ultra successes (in addition to the usual bonus). No identifiers will remain—not even teeth.

**46. MENACING:** Enemies who see a comrade slain by this weapon have a 1-in-1D6 chance to flee.

**51. NON-LETHAL:** Does not deal DAMAGE; has a 3-in-1D6 chance to knock unconscious on a success.

**52. POISONED:** When you would roll for damage for this weapon, wait and mark your target as poisoned instead. Next time they’re hurt, roll your DAMAGE and add it to the total amount they take.

**53. PROTOTYPE:** Wielding this next-generation weapon grants +1 EYES; roll +EYES to attack with it.

**54. QUICK-DRAW:** Attacks that target enemies drawing their weapons will always succeed.

**55. REMOTE:** Projectiles (or the weapon itself) can be remotely steered through chutes and around walls.

**56. RITUAL:** Shatters to protect you from death once, negating lethal damage. Disintegrates afterward.

**61. SAPIENT:** Communicates with its wielder by thought; roll 1D6 for disposition: bloodthirsty, caring, craven, excitable, morose, stoic.

**62. SHREDDER:** Deals double DAMAGE to exposed flesh. On critical hits, decreases the target’s ARMOR by 1.

**63. STUN:** Those damaged by this weapon cannot move or act until their current HP changes.

**64. TRANQUILIZER:** As NON-LETHAL, but chance is increased to 5-in-1D6 if a vulnerable area is specifically targeted (e.g. head, neck, exposed membrane, etc.)

**65. UNSTABLE:** Can be set to overload to deal triple DAMAGE once; explodes for 3D6 damage to everyone nearby seconds later.

**66. VALUABLE:** Utterly unique in history or make. Can be used as a bargaining chip in almost any situation.