---
title: "Attributes"
editor: 
  markdown: 
    wrap: sentence
---

There are four attributes for characters; EYES, TEETH, LIMBS, and HEART.
Whenever a player controlled character carried out an action they roll 2D6 and add the modifier of the relevant attribute. This is known as rolling +ATTRIBUTE (+EYES, +TEETH, +LIMBS, or +HEART)
This determines how successful they are.

- 6 or less: Failure
- 7-9: Partial success
- 10+: Full success
- 2 6s: Ultra success

An action is any task or activity the player wishes the character to do that is considered risky or has a strong element of chance.
Most activities inside combat count as actions.
Outside combat trivial tasks will be handled with narration rather than rolls.

The attribute chosen for an action is initially chosen by the player performing the action.
If the referee is not happy with the choice the player can attempt to further explain, change the action to fit the attribute, or be content in the referee choosing a more appropriate attribute.

## The Attributes

The four attributes as tied to the four [Primeval deities](https://m-gemmell.github.io/Primeval_Deities_FIST/). 
Conveniently they are also analogs of the four attributes in FIST so FIST traits can be used in PUML and vice versa.

- EYES = TACTICAL
- TEETH = FORCEFUL
- LIMBS = REFLEXIVE
- BRAIN = CREATIVE

### EYES

[Nyxmera](https://m-gemmell.github.io/Primeval_Deities_FIST/nyxmera.html) is the deity of the sky.
Its eyes are the sun, stars, planets, and moons in the sky.
__NYXMERA__ loves to watch, enjoying drama and comedy.
It is clever and loves to scheme.

You can roll __+EYES__ for assessing and manipulating a situation.

These include:

- Knowledge-based tasks
- Tactical manoeuvres
- Technical operations
  - E.g engineering, cyber security, medical response, and controlling machinery
- Reconnaissance & Research
- Imitating and appreciating the arts
- Astral powers

### TEETH

[Tartarus](https://m-gemmell.github.io/Primeval_Deities_FIST/tartarus.html) is the deity of the earth.
Its mouths are the entrances into its domain and its prison, The DOT.
It is angry and destructive.

You can roll __+TEETH__ for bouts of strength, violence, or rage.

These include:

- Strength-based tasks
- Aggressive manoeuvres
- Destruction
- Intimidation
- Freeing the imprisoned
- Earth and fire powers

### LIMBS

[Proteus](https://m-gemmell.github.io/Primeval_Deities_FIST/proteus.html) is the deity of water.
Its limbs represent how it reaches into and shapes living systems whilst in turn being shaped by them.
It is adaptable, calm, and flowing.

You can roll __+LIMBS__ for fast and fluid movements.

These include:

- Dexterity-based tasks
- Reflexive manoeuvres
- Use of steady hands and body
- Blending in
- Going with the flow
- Water powers

### BRAIN

[Gaia](https://m-gemmell.github.io/Primeval_Deities_FIST/gaia.html) is the deity of life.
Its brain is the unity of all life, creating a hyperorganism.
It is social and mystical.

You can roll __+BRAIN__ for human and paranormal interactions.

These include:

- Charisma-based tasks
- Diplomatic manoeuvres
- Leadership and persuasion
- Implementation of unique and creative ideas
- Unification
- Life and mind powers